version: '3.8'

services:
  global_db:
    image: postgres:13
    environment:
      POSTGRES_DB: vetchium_global
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./global_schema.sql:/docker-entrypoint-initdb.d/global_schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vetchium_global"]
      interval: 5s
      timeout: 5s
      retries: 5

  regional_db:
    image: postgres:13
    environment:
      POSTGRES_DB: vetchium_regional
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./regional_schema.sql:/docker-entrypoint-initdb.d/regional_schema.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vetchium_regional"]
      interval: 5s
      timeout: 5s
      retries: 5
