services:
  global_db:
    image: postgres:16
    environment:
      POSTGRES_DB: vetchium_global
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./global_schema.sql:/docker-entrypoint-initdb.d/global_schema.sql
      - global_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vetchium_global"]
      interval: 5s
      timeout: 5s
      retries: 5

  regional_db_eu_dev:
    image: postgres:16
    environment:
      POSTGRES_DB: vetchium_regional_eu_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./regional_schema.sql:/docker-entrypoint-initdb.d/regional_schema.sql
      - eu_dev_data:/var/lib/postgresql/data
    ports:
      - "6001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vetchium_regional_eu_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  regional_db_in_dev:
    image: postgres:16
    environment:
      POSTGRES_DB: vetchium_regional_in_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./regional_schema.sql:/docker-entrypoint-initdb.d/regional_schema.sql
      - in_dev_data:/var/lib/postgresql/data
    ports:
      - "6002:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vetchium_regional_in_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  global_db_data:
  eu_dev_data:
  in_dev_data: